### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-ci#1220]
To integrate better with different third-party services, it would be great to be able to add "links" to builds and/or jobs.

Each link will have a URL, a "source name" and a description. The resulting code to be displayed should be something like this:

``` HTML
<a href="{{ url }}">{{ source_name }}</a>: {{ description }}
```
## TODO
- [x] Decide what information should be included in each link. My suggestions are above.
- [x] Add model and table in core
- [x] Decide how to authenticate adding the links
- [x] Add API endpoint to create links
- [x] Add the links to the web UI
- [x] Add support to `travis-ci/travis`
