### ISSUE TITLE
Handle errors in .travis.yml better

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-ci#1223]
A `.travis.yml` file can have many issues with it. I'm opening this issue to keep track of some ideas for how to make it easier to debug .travis.yml issues.

Basically what I'd like is to write a spec of sorts for the `.travis.yml` file, probably in a machine-readable format. We can then generate some documentation from that, as well as a tool á là travis-lint that checks the `.travis.yml` file. This should be run on every build and either error the build or print a warning if something is wrong.

Having this also forces us to document our changes to the `.travis.yml` format, which I think is a good thing.
## TODO
- [x] Show a nice error for YAML parse errors.
- [x] Decide on a spec format for `.travis.yml`.
- [x] Create a tool that reads the spec and a `.travis.yml` and warns about any errors.
- [ ] Make builds error if the tool reports any warnings, or at least run the tool and print out any warnings on the builds.
