### ISSUE TITLE
OAuth support

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#1225]
Our current OAuth support is … lacking, at best. This issue is open to track expanding the OAuth support to something that's fairly usable.

Below are some TODOs in roughly the order I think they should be implemented, making OAuth support better and better as we go (not everything is needed to make OAuth usable).
## TODO
- [ ] Add `OAuthApplication` model, which tracks client IDs and secrets.
- [ ] Add UI to authorize an application (ie. create an access token)
- [ ] Add `OAuthAuthorization` model, which contains the user and application for the authorization, as well as any scopes
- [ ] Add UI to revoke tokens.
- [ ] Figure out what kinds of scopes we want (probably at least readonly + readwrite).
- [ ] Connect access tokens to authorizations. (Maybe they should be embedded in the `OAuthAuthorization` model?)
- [ ] Add UI to create `OAuthApplication`s

**Comment by BanzaiMan** [comment]
Closing this for now. We may come back to it in the future.
