### ISSUE TITLE
Technical issues implementing Windows support

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#2104]
## Note

We recognize that there is an overwhelming demand for Windows support on Travis CI.

This ticket aims to keep track of the technical issues involved in realizing it. As such, please refrain from commenting with just :+1: without any technical input. We will remove such comments on this ticket.
# Scope

Our initial focus is to run Travis CI builds on Windows workers.
1. Boot a Windows VM
2. Compile a build script similar to the one as we do now in Linux and OS X
3. Allow comparable customizations by the user (auxiliary services, etc.)
## Things not covered in scope (at least initially)
1. Multi-OS support
2. Multi-Windows-version support (This might be a reasonable feature, but I do not yet know difficult it would be.)
# Tasks
- [ ] Implement ability to boot a Windows VM (on Azure primarily, and other cloud providers possibly)
- [ ] Add to [travis-build](https://github.com/travis-ci/travis-build) the ability to generate a build script for Windows host. For this, we believe PowerShell is the most reasonable choice as the language.
- [ ] Adapt [travis-cookbooks](https://github.com/travis-ci/travis-cookbooks) to run on Windows host. (Tangentially, investigate [test-kitchen](https://github.com/test-kitchen/test-kitchen) for testing our cookbooks).

**Comment by vbauer** [comment]
:+1:

**Comment by tresf** [comment]
Perhaps one obstacle worth mentioning for Windows build support is deciding which package managers to support caching for.  I'm not sure how common cross-compilation support on Windows is, but our cmake recipes make this possible and our dependency listing is on the large size (~1GB) so we may be a good use case to help test Windows building out, once available.

From the C++ side of the dependency fence, we (LMMS) are putting some time into supporting msys2 due to a hard-dependency on mingw-w64 (not to be confused with mingw32) for compilation and the classic solutions: `cygwin`, `original msys` and `mingw32` don't suit our needs.

msys2's port of `pacman` relies on sourceforge mirrors (much like MacPorts) for fulfilling dependencies which seem to work only about 90% of the time.   Retrying fixes things, but this could be something where travis mirror caching could really help. 

Today (naturally), our `.travis.yml` doesn't contain the logic necessary to fire this off just yet, but I at least wanted to chime in that our team would be happy to some testing if and when this feature becomes available.

**Comment by tianon** [comment]
Does the new GCE architecture help at all with implementation of this? :smile:

**Comment by GeARCraft1** [comment]
I Think I can help in these 3 steps, using lots of powershell and .NET. Contact me via e-mail: enricorocha1@hotmail.com

**Comment by joshk** [comment]
I am interested in starting a Slack channel where we can discuss this. 

I think we can break this down further and make it easier.

Please email me at josh at travis-ci dot com if you are interested in joining the chat.

**Comment by bradrothenberg** [comment]
any update on windows support?

**Comment by fracting** [comment]
Hi all, welcome to try https://www.tea-ci.org

Tea CI is a continuous integration service for Windows applications, free for open source developers.
Tea CI runs on Linux + Docker + Drone + Wine.

Any feedback is great appreciated.

To Travis CI team:
I'm Qian Hong, a Wine contributor and a Msys2 contributor, also the creator of Tea CI. More than one year ago, I wrote an email to Travis CI support for volunteering to provide a CI solution for Windows build with Wine, but my suggestion did not convinced Travis CI team at that time, so I created my own Tea CI service to serve open source developers. If any time Travis CI team would like to support Windows build using Wine, I'm always here to help, I'm glad to be contacted either publicly or privately.

**Comment by levithatcher** [comment]
Any update for Windows support? We've been loving travis-ci and have been huge evangelists for it!

**Comment by jayvdb** [comment]
https://www.tea-ci.org (redirecting to docs...) is timing out for me. https://tea-ci.org/ is working, but is a little slow.

**Comment by fracting** [comment]
> But if tea-ci is only Wine, that can be done fairly easily on Travis by installing wine on a standard image, or rolling your own image.

Initially we began from trying Wine on Travis CI, but it ends up with some corner cases which can't be controlled by end user but affects Wine functionality, for example the aufs filesystem using by Travis CI breaks Wine extent attributes: https://bugs.wine-staging.com/show_bug.cgi?id=403

That's why we end up with an open source environment with fully control.

I'm always happy to see more users using Wine, if anyone has universal solution for Wine on Travis CI please share! If Travis CI works great with Wine, I'm glad to help Tea CI users transfer to Travis CI, otherwise I'm glad to receive any contribution / volunteer to Tea CI :)

**Comment by BanzaiMan** [comment]
If you want to discuss tea-ci.org, please use a different venue to do so.

I am locking this one until we have other issues to discuss.
